name: flutter_map_marker_popup_example
description: Example for Flutter Map Marker Popups.
publish_to: 'none'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.9.1
  flutter_map: ^6.0.1
  flutter_map_marker_popup:
    path: ../

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf
